repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.1.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-merge-conflict
          - id: check-yaml
          - id: end-of-file-fixer
          - id: requirements-txt-fixer
          - id: sort-simple-yaml
          - id: trailing-whitespace
    - repo: local
      hooks:
          - id: sort-imports
            name: sort-imports
            entry: yarn import-sort
            language: system
            files: \.js$
            args: ['--write']
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.5.1
      hooks:
          - id: prettier
